# Generated by Django 5.1.4 on 2025-01-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='chat_room',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
