# Generated by Django 5.1.4 on 2025-01-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message_Chat_app', '0001_initial'),
        ('scheduler', '0002_schedule_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
