# Generated by Django 5.1.5 on 2025-01-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message_Chat_app', '0002_chatmessage_schedule_alter_chatmessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
